---
title: "7th Chapter"
author: "Mykola Dereva"
date: "4/22/2021"
output: html_document
---

```{r}
library(tidyverse)
library(tidybayes)
library(brms)
```



```{r}
d <-
  tibble(z1 = 6, 
         z2 = 2,
         n1 = 8,
         n2 = 7)

d
```


```{r}
model_1 <- bf(z1 | trials(n1) ~ 1)
model_2 <- bf(z2 | trials(n2) ~ 1)
```


```{r}
fit7.1 <-
  brm(data = d, 
      family = binomial(),
      model_1 + model_2,
      prior(normal(0, 1), class = Intercept),
      iter = 25500, warmup = 500, cores = 1, chains = 1,
      seed = 7,
      file = "fits/fit07.01")
```


```{r}
print(fit7.1)
```


```{r}
fixef(fit7.1)[, 1] %>% inv_logit_scaled()
```


```{r}
post <- posterior_samples(fit7.1, add_chain = T)
```


```{r}
post %>% 
  mutate(theta_1 = b_z1_Intercept %>% inv_logit_scaled(), 
         theta_2 = b_z2_Intercept %>% inv_logit_scaled()) %>% 
  filter(iter < 1001) %>% 
  
  ggplot(aes(x = theta_1, y = theta_2)) +
  geom_point(alpha = 1/4, color = "steelblue") +
  geom_path(size = 1/10, alpha = 1/2, color = "steelblue") +
  scale_x_continuous(expression(theta[1]), expand = expansion(mult = 0),
                     limits = c(0, 1)) +
  scale_y_continuous(expression(theta[2]), expand = expansion(mult = 0),
                     limits = c(0, 1)) +
  coord_equal() 
```


```{r}
post %>% 
  mutate(`theta[1]` = b_z1_Intercept %>% inv_logit_scaled(), 
         `theta[2]` = b_z2_Intercept %>% inv_logit_scaled()) %>% 
  pivot_longer(`theta[1]`:`theta[2]`) %>% 
  
  ggplot(aes(x = value, y = name)) +
  stat_halfeye(point_interval = mode_hdi, .width = c(.5, .95), fill = "steelblue") +
  scale_y_discrete(NULL, labels = ggplot2:::parse_safe, expand = expansion(mult = 0)) +
  xlab("posterior") 
```




```{r}
z <- 35
n <- 50

d <- tibble(y = rep(0:1, times = c(n - z, z)))
```


```{r}
fit7.2 <-
  brm(data = d, 
      family = bernoulli(link = identity),
      y ~ 1,
      prior(beta(2, 2), class = Intercept),
      iter = 10000, warmup = 500, cores = 3, chains = 3,
      control = list(adapt_delta = 0.9),
      seed = 7,
      file = "fits/fit07.02")
```



```{r}
plot(fit7.2)
```



```{r}
warmups <-
  c(fit7.2$fit@sim$samples[[1]]$b_Intercept[1:500], 
    fit7.2$fit@sim$samples[[2]]$b_Intercept[1:500], 
    fit7.2$fit@sim$samples[[3]]$b_Intercept[1:500]) %>% 
  # since these come from lists, here we'll convert them to a data frame
  as.data.frame() %>% 
  rename(b_Intercept = ".") %>% 
  # we'll need to recapture the iteration and chain information
  mutate(iter  = rep(1:500, times = 3),
         chain = factor(rep(1:3, each = 500), 
                        levels = c("1", "2", "3")))

warmups %>% 
  head()
```


```{r}
library(bayesplot)
```


```{r}
mcmc_trace(warmups, pars = "b_Intercept")
```


```{r}
# install.packages("ggmcmc", dependencies = T)
library(ggmcmc)
```


```{r}
ggs(fit7.2) %>%
  filter(Iteration < 501 &
           Parameter == "b_Intercept") %>% 
  mutate(chain = factor(Chain)) %>% 
  
  ggplot(aes(x = Iteration, y = value, color = chain)) +
  geom_line() +
  scale_colour_brewer(direction = -1) +
  labs(title = "My custom trace plots with warmups via ggmcmc::ggs()",
       x = NULL, y = NULL) +
  theme_minimal()
```


```{r}
mcmc_acf(warmups, pars = "b_Intercept", lags = 25)
```


```{r}
mcmc_acf(warmups)$data %>% 
  as_tibble() %>% 
  filter(Parameter == "b_Intercept") %>% 
  
  ggplot(aes(x = Lag, y = AC,
             color = Chain %>% as.factor())) +
  geom_hline(yintercept = 0, color = "white") +
  geom_point(size = 2/3) +
  geom_line() +
  scale_colour_brewer(direction = -1) +
  ylab("Autocorrelation") +
  theme_minimal() +
  theme(legend.position = "none") 

```


```{r}
mcmc_dens_overlay(warmups, pars = c("b_Intercept"))
```


Now plot actual samples

```{r}
post <- posterior_samples(fit7.2, add_chain = T)

mcmc_trace(post, pars = "b_Intercept")
```


```{r}
mcmc_acf(post, pars = "b_Intercept", lags = 20)
```


```{r}
mcmc_dens_overlay(post, pars = c("b_Intercept"))
```


```{r}
fit7.2_c <- as.mcmc(fit7.2)

fit7.2_c %>% glimpse()
```


```{r}
coda::gelman.plot(fit7.2_c[, "b_Intercept", ])
```


```{r}
print(fit7.2)
```


```{r}
post %>% 
  ggplot(aes(x = b_Intercept, y = chain, fill = chain)) +
  stat_halfeye(point_interval = mode_hdi,
                .width = .95) +
  scale_fill_brewer(direction = -1) +
  scale_y_discrete(expand = expansion(mult = 0.025)) +
  theme_minimal() +
  theme(legend.position = "none")
```


```{r}
bayesplot::mcmc_acf_bar(post,
             pars = "b_Intercept",
             lags = 20)
```

